-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then
  vim.cmd 'highlight clear'
end
vim.g.colors_name = 'kanso-zen'

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, '@attribute', { link = 'Constant' })
hi(0, '@attribute.builtin', { link = 'Special' })
hi(0, '@character.special', { link = 'SpecialChar' })
hi(0, '@comment.error', { bg = '#c34043', bold = true, fg = '#b1d1c1' })
hi(0, '@comment.note', { bg = '#6a9589', bold = true, fg = '#193154' })
hi(0, '@comment.todo', { link = 'Todo' })
hi(0, '@comment.warning', { bg = '#dca561', bold = true, fg = '#193154' })
hi(0, '@constant.builtin', { link = 'Special' })
hi(0, '@constructor', { fg = '#cdb070' })
hi(0, '@constructor.lua', { fg = '#97a7cb' })
hi(0, '@diff.delta', { fg = '#e8a03d' })
hi(0, '@diff.minus', { fg = '#d41d32' })
hi(0, '@diff.plus', { fg = '#6a9956' })
hi(0, '@function.builtin', { link = 'Special' })
hi(0, '@ibl.indent.char.1', { fg = '#1b2639', nocombine = true })
hi(0, '@ibl.scope.char.1', { fg = '#33395b', nocombine = true })
hi(0, '@ibl.scope.underline.1', { nocombine = true, sp = '#393b44', underline = true })
hi(0, '@ibl.whitespace.char.1', { fg = '#1b2639', nocombine = true })
hi(0, '@keyword.exception', { fg = '#97a7cb' })
hi(0, '@keyword.import', { link = 'PreProc' })
hi(0, '@keyword.luap', { link = '@string.regex' })
hi(0, '@keyword.operator', { fg = '#8394af' })
hi(0, '@keyword.return', { fg = '#97a7cb', italic = true })
hi(0, '@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi(0, '@lsp.mod.readonly', { link = 'Constant' })
hi(0, '@lsp.mod.typeHint', { link = 'Type' })
hi(0, '@lsp.type.bitwise', { link = 'Operator' })
hi(0, '@lsp.type.builtinConstant', { link = '@constant.builtin' })
hi(0, '@lsp.type.class', { link = '@type' })
hi(0, '@lsp.type.comment', { link = 'Comment' })
hi(0, '@lsp.type.comparison', { link = 'Operator' })
hi(0, '@lsp.type.const', { link = 'Constant' })
hi(0, '@lsp.type.decorator', { link = '@attribute' })
hi(0, '@lsp.type.decorator.rust', { link = 'PreProc' })
hi(0, '@lsp.type.enum', { link = '@type' })
hi(0, '@lsp.type.enumMember', { link = '@constant' })
hi(0, '@lsp.type.event', { link = '@type' })
hi(0, '@lsp.type.function', { link = '@function' })
hi(0, '@lsp.type.interface', { link = '@type' })
hi(0, '@lsp.type.keyword', { link = '@keyword' })
hi(0, '@lsp.type.lifetime', { link = 'Operator' })
hi(0, '@lsp.type.macro', { link = 'Macro' })
hi(0, '@lsp.type.magicFunction', { link = '@function.builtin' })
hi(0, '@lsp.type.method', { link = '@function.method' })
hi(0, '@lsp.type.modifier', { link = '@type.qualifier' })
hi(0, '@lsp.type.namespace', { link = '@module' })
hi(0, '@lsp.type.number', { link = '@number' })
hi(0, '@lsp.type.operator', { link = '@operator' })
hi(0, '@lsp.type.parameter', { link = '@variable.parameter' })
hi(0, '@lsp.type.property', { link = '@property' })
hi(0, '@lsp.type.punctuation', { link = 'Delimiter' })
hi(0, '@lsp.type.regexp', { link = '@string.regexp' })
hi(0, '@lsp.type.selfParameter', { link = '@variable.builtin' })
hi(0, '@lsp.type.string', { link = '@string' })
hi(0, '@lsp.type.struct', { link = '@type' })
hi(0, '@lsp.type.type', { link = '@type' })
hi(0, '@lsp.type.typeParameter', { link = '@type.definition' })
hi(0, '@lsp.type.variable', {})
hi(0, '@lsp.typemod.function.builtin', { link = '@function.builtin' })
hi(0, '@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.function.readonly', { bold = true, fg = '#77a7be' })
hi(0, '@lsp.typemod.keyword.documentation', { link = 'Special' })
hi(0, '@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
hi(0, '@lsp.typemod.operator.controlFlow', { link = '@keyword.exception' })
hi(0, '@lsp.typemod.variable.defaultLibrary', { link = 'Special' })
hi(0, '@lsp.typemod.variable.global', { link = 'Constant' })
hi(0, '@lsp.typemod.variable.injected', { link = '@variable' })
hi(0, '@lsp.typemod.variable.static', { link = 'Constant' })
hi(0, '@markup.environment', { link = 'Keyword' })
hi(0, '@markup.heading', { link = 'Function' })
hi(0, '@markup.heading.1.delimiter.vimdoc', { bg = '#090e13', fg = '#060e17', nocombine = true, sp = '#c5c9c7', underdouble = true })
hi(0, '@markup.heading.2.delimiter.vimdoc', { bg = '#090e13', fg = '#060e17', nocombine = true, sp = '#c5c9c7', underline = true })
hi(0, '@markup.link', { link = 'Underlined' })
hi(0, '@markup.link.url', { link = '@string.special.url' })
hi(0, '@markup.math', { link = 'Constant' })
hi(0, '@markup.quote', { link = '@variable.parameter' })
hi(0, '@markup.raw', { link = 'String' })
hi(0, '@module.builtin', { link = 'Special' })
hi(0, '@number.float', { link = 'Float' })
hi(0, '@punctuation.bracket', { fg = '#8394af' })
hi(0, '@punctuation.delimiter', { fg = '#8394af' })
hi(0, '@punctuation.special', { fg = '#cdb070' })
hi(0, '@string.escape', { fg = '#da635d' })
hi(0, '@string.regexp', { fg = '#da635d' })
hi(0, '@string.special', { link = 'SpecialChar' })
hi(0, '@string.special.symbol', { fg = '#97a7cb' })
hi(0, '@string.special.url', { fg = '#cdb070', undercurl = true })
hi(0, '@tag.attribute', { fg = '#97a7cb' })
hi(0, '@tag.builtin', { link = 'Special' })
hi(0, '@tag.delimiter', { fg = '#8394af' })
hi(0, '@type.builtin', { link = 'Special' })
hi(0, '@variable', { fg = '#b1d1c1' })
hi(0, '@variable.builtin', { fg = '#97a7cb', italic = true })
hi(0, '@variable.member', { fg = '#97a7cb' })
hi(0, '@variable.parameter', { fg = '#8394af' })
hi(0, '@variable.parameter.builtin', { link = 'Special' })
hi(0, 'Added', { ctermfg = 10, fg = '#a0fcb4' })
hi(0, 'AerialArrayIcon', { link = 'Type' })
hi(0, 'AerialBooleanIcon', { link = 'Boolean' })
hi(0, 'AerialClassIcon', { link = 'Type' })
hi(0, 'AerialConstantIcon', { link = 'Constant' })
hi(0, 'AerialConstructorIcon', { link = '@constructor' })
hi(0, 'AerialEnumIcon', { link = 'Type' })
hi(0, 'AerialEnumMemberIcon', { link = 'Constant' })
hi(0, 'AerialEventIcon', { link = 'Structure' })
hi(0, 'AerialFieldIcon', { link = '@variable.member' })
hi(0, 'AerialFileIcon', { link = 'Directory' })
hi(0, 'AerialFunctionIcon', { link = 'Function' })
hi(0, 'AerialInterfaceIcon', { link = 'Type' })
hi(0, 'AerialKeyIcon', { link = 'Identifier' })
hi(0, 'AerialMethodIcon', { link = '@function.method' })
hi(0, 'AerialModuleIcon', { link = '@module' })
hi(0, 'AerialNamespaceIcon', { link = '@module' })
hi(0, 'AerialNullIcon', { link = 'Type' })
hi(0, 'AerialNumberIcon', { link = 'Number' })
hi(0, 'AerialObjectIcon', { link = 'Type' })
hi(0, 'AerialOperatorIcon', { link = 'Operator' })
hi(0, 'AerialPackageIcon', { link = '@module' })
hi(0, 'AerialPropertyIcon', { link = '@property' })
hi(0, 'AerialStringIcon', { link = 'String' })
hi(0, 'AerialStructIcon', { link = 'Structure' })
hi(0, 'AerialTypeParameterIcon', { link = 'Type' })
hi(0, 'AerialVariableIcon', { link = '@variable' })
hi(0, 'BlinkCmpDoc', { link = 'NormalFloat' })
hi(0, 'BlinkCmpDocBorder', { link = 'FloatBorder' })
hi(0, 'BlinkCmpDocCursorLine', { link = 'Visual' })
hi(0, 'BlinkCmpGhostText', { fg = '#657a9a' })
hi(0, 'BlinkCmpKind', { fg = '#93af93' })
hi(0, 'BlinkCmpKindClass', { link = 'Type' })
hi(0, 'BlinkCmpKindColor', { link = 'Special' })
hi(0, 'BlinkCmpKindConstant', { link = 'Constant' })
hi(0, 'BlinkCmpKindConstructor', { link = '@constructor' })
hi(0, 'BlinkCmpKindCopilot', { link = 'String' })
hi(0, 'BlinkCmpKindEnum', { link = 'Type' })
hi(0, 'BlinkCmpKindEnumMember', { link = 'Constant' })
hi(0, 'BlinkCmpKindEvent', { link = 'Type' })
hi(0, 'BlinkCmpKindField', { link = '@variable.member' })
hi(0, 'BlinkCmpKindFile', { link = 'Directory' })
hi(0, 'BlinkCmpKindFolder', { link = 'Directory' })
hi(0, 'BlinkCmpKindFunction', { link = 'Function' })
hi(0, 'BlinkCmpKindInterface', { link = 'Type' })
hi(0, 'BlinkCmpKindKeyword', { link = 'Keyword' })
hi(0, 'BlinkCmpKindMethod', { link = '@function.method' })
hi(0, 'BlinkCmpKindModule', { link = '@module' })
hi(0, 'BlinkCmpKindOperator', { link = 'Operator' })
hi(0, 'BlinkCmpKindProperty', { link = '@property' })
hi(0, 'BlinkCmpKindReference', { link = 'Special' })
hi(0, 'BlinkCmpKindSnippet', { link = 'Special' })
hi(0, 'BlinkCmpKindStruct', { link = 'Type' })
hi(0, 'BlinkCmpKindText', { fg = '#b1d1c1' })
hi(0, 'BlinkCmpKindTypeParameter', { link = 'Type' })
hi(0, 'BlinkCmpKindUnit', { link = 'Number' })
hi(0, 'BlinkCmpKindValue', { link = 'String' })
hi(0, 'BlinkCmpKindVariable', { fg = '#93af93' })
hi(0, 'BlinkCmpLabel', { fg = '#f5f1e8' })
hi(0, 'BlinkCmpLabelDeprecated', { fg = '#657a9a', strikethrough = true })
hi(0, 'BlinkCmpLabelDetails', { fg = '#657a9a' })
hi(0, 'BlinkCmpLabelMatch', { fg = '#77a7be' })
hi(0, 'BlinkCmpMenu', { link = 'Pmenu' })
hi(0, 'BlinkCmpMenuBorder', { bg = '#090e13', fg = '#1e5070' })
hi(0, 'BlinkCmpMenuSelection', { link = 'PmenuSel' })
hi(0, 'BlinkCmpScrollBarGutter', { link = 'PmenuSbar' })
hi(0, 'BlinkCmpScrollBarThumb', { link = 'PmenuThumb' })
hi(0, 'BlinkCmpSignatureHelp', { link = 'NormalFloat' })
hi(0, 'BlinkCmpSignatureHelpActiveParameter', { link = 'LspSignatureActiveParameter' })
hi(0, 'BlinkCmpSignatureHelpBorder', { link = 'FloatBorder' })
hi(0, 'Bold', { bold = true })
hi(0, 'Boolean', { fg = '#c68c65' })
hi(0, 'BufferLineBackground', { fg = '#4f617c' })
hi(0, 'BufferLineBuffer', { fg = '#4f617c' })
hi(0, 'BufferLineBufferSelected', { bold = true, fg = '#b1d1c1' })
hi(0, 'BufferLineBufferVisible', { fg = '#93af93' })
hi(0, 'BufferLineCloseButton', { fg = '#4f617c' })
hi(0, 'BufferLineCloseButtonSelected', { fg = '#b1d1c1' })
hi(0, 'BufferLineCloseButtonVisible', { fg = '#93af93' })
hi(0, 'BufferLineDevIconLua', { fg = '#4f617c' })
hi(0, 'BufferLineDevIconLuaInactive', { fg = '#4f617c' })
hi(0, 'BufferLineDuplicate', { fg = '#4f617c' })
hi(0, 'BufferLineDuplicateSelected', { bold = true, fg = '#b1d1c1' })
hi(0, 'BufferLineDuplicateVisible', { fg = '#93af93' })
hi(0, 'BufferLineError', { fg = '#4f617c' })
hi(0, 'BufferLineErrorDiagnostic', { fg = '#4f617c' })
hi(0, 'BufferLineErrorDiagnosticSelected', { bold = true, fg = '#d41d32' })
hi(0, 'BufferLineErrorDiagnosticVisible', { fg = '#d41d32' })
hi(0, 'BufferLineErrorSelected', { bold = true, fg = '#d41d32' })
hi(0, 'BufferLineErrorVisible', { fg = '#d41d32' })
hi(0, 'BufferLineHint', { fg = '#4f617c' })
hi(0, 'BufferLineHintDiagnostic', { fg = '#4f617c' })
hi(0, 'BufferLineHintDiagnosticSelected', { bold = true, fg = '#569a88' })
hi(0, 'BufferLineHintDiagnosticVisible', { fg = '#569a88' })
hi(0, 'BufferLineHintSelected', { bold = true, fg = '#569a88' })
hi(0, 'BufferLineHintVisible', { fg = '#569a88' })
hi(0, 'BufferLineIndicatorSelected', { fg = '#4f617c' })
hi(0, 'BufferLineIndicatorVisible', { fg = '#4f617c' })
hi(0, 'BufferLineInfo', { fg = '#4f617c' })
hi(0, 'BufferLineInfoDiagnostic', { fg = '#4f617c' })
hi(0, 'BufferLineInfoDiagnosticSelected', { bold = true, fg = '#53889f' })
hi(0, 'BufferLineInfoDiagnosticVisible', { fg = '#53889f' })
hi(0, 'BufferLineInfoSelected', { bold = true, fg = '#53889f' })
hi(0, 'BufferLineInfoVisible', { fg = '#53889f' })
hi(0, 'BufferLineModified', { fg = '#e8a03d' })
hi(0, 'BufferLineModifiedSelected', { bold = true, fg = '#e8a03d' })
hi(0, 'BufferLineModifiedVisible', { fg = '#e8a03d' })
hi(0, 'BufferLineNumbers', { fg = '#4f617c' })
hi(0, 'BufferLineNumbersSelected', { bold = true, fg = '#b1d1c1' })
hi(0, 'BufferLineNumbersVisible', { fg = '#93af93' })
hi(0, 'BufferLineOffsetSeparator', { fg = '#4f617c' })
hi(0, 'BufferLinePick', { bold = true, fg = '#cdb070' })
hi(0, 'BufferLinePickSelected', { bold = true, fg = '#cdb070' })
hi(0, 'BufferLinePickVisible', { bold = true, fg = '#cdb070' })
hi(0, 'BufferLineSeparator', { fg = '#4f617c' })
hi(0, 'BufferLineSeparatorSelected', { fg = '#4f617c' })
hi(0, 'BufferLineSeparatorVisible', { fg = '#4f617c' })
hi(0, 'BufferLineTab', { fg = '#4f617c' })
hi(0, 'BufferLineTabClose', { fg = '#4f617c' })
hi(0, 'BufferLineTabSelected', { bold = true, fg = '#b1d1c1' })
hi(0, 'BufferLineTabSeparator', { fg = '#4f617c' })
hi(0, 'BufferLineTabSeparatorSelected', { fg = '#4f617c' })
hi(0, 'BufferLineTruncMarker', { fg = '#4f617c' })
hi(0, 'BufferLineWarning', { fg = '#4f617c' })
hi(0, 'BufferLineWarningDiagnostic', { fg = '#4f617c' })
hi(0, 'BufferLineWarningDiagnosticSelected', { bold = true, fg = '#e8a03d' })
hi(0, 'BufferLineWarningDiagnosticVisible', { fg = '#e8a03d' })
hi(0, 'BufferLineWarningSelected', { bold = true, fg = '#e8a03d' })
hi(0, 'BufferLineWarningVisible', { fg = '#e8a03d' })
hi(0, 'Changed', { ctermfg = 14, fg = '#65fdfd' })
hi(0, 'Character', { link = 'String' })
hi(0, 'CmpCompletion', { link = 'Pmenu' })
hi(0, 'CmpCompletionBorder', { bg = '#090e13', fg = '#1e5070' })
hi(0, 'CmpCompletionSbar', { link = 'PmenuSbar' })
hi(0, 'CmpCompletionSel', { link = 'PmenuSel' })
hi(0, 'CmpCompletionThumb', { link = 'PmenuThumb' })
hi(0, 'CmpDocumentation', { link = 'NormalFloat' })
hi(0, 'CmpDocumentationBorder', { link = 'FloatBorder' })
hi(0, 'CmpGhostText', { fg = '#657a9a' })
hi(0, 'CmpItemAbbr', { fg = '#f5f1e8' })
hi(0, 'CmpItemAbbrDeprecated', { fg = '#657a9a', strikethrough = true })
hi(0, 'CmpItemAbbrMatch', { fg = '#77a7be' })
hi(0, 'CmpItemAbbrMatchFuzzy', { link = 'CmpItemAbbrMatch' })
hi(0, 'CmpItemKindClass', { link = 'Type' })
hi(0, 'CmpItemKindColor', { link = 'Special' })
hi(0, 'CmpItemKindConstant', { link = 'Constant' })
hi(0, 'CmpItemKindConstructor', { link = '@constructor' })
hi(0, 'CmpItemKindCopilot', { link = 'String' })
hi(0, 'CmpItemKindDefault', { fg = '#93af93' })
hi(0, 'CmpItemKindEnum', { link = 'Type' })
hi(0, 'CmpItemKindEnumMember', { link = 'Constant' })
hi(0, 'CmpItemKindEvent', { link = 'Type' })
hi(0, 'CmpItemKindField', { link = '@variable.member' })
hi(0, 'CmpItemKindFile', { link = 'Directory' })
hi(0, 'CmpItemKindFolder', { link = 'Directory' })
hi(0, 'CmpItemKindFunction', { link = 'Function' })
hi(0, 'CmpItemKindInterface', { link = 'Type' })
hi(0, 'CmpItemKindKeyword', { link = 'Keyword' })
hi(0, 'CmpItemKindMethod', { link = '@function.method' })
hi(0, 'CmpItemKindModule', { link = '@module' })
hi(0, 'CmpItemKindOperator', { link = 'Operator' })
hi(0, 'CmpItemKindProperty', { link = '@property' })
hi(0, 'CmpItemKindReference', { link = 'Special' })
hi(0, 'CmpItemKindSnippet', { link = 'Special' })
hi(0, 'CmpItemKindStruct', { link = 'Type' })
hi(0, 'CmpItemKindText', { fg = '#b1d1c1' })
hi(0, 'CmpItemKindTypeParameter', { link = 'Type' })
hi(0, 'CmpItemKindUnit', { link = 'Number' })
hi(0, 'CmpItemKindValue', { link = 'String' })
hi(0, 'CmpItemKindVariable', { fg = '#93af93' })
hi(0, 'CmpItemMenu', { fg = '#93af93' })
hi(0, 'ColorColumn', { bg = '#1c1e25' })
hi(0, 'Comment', { fg = '#657a9a', italic = true })
hi(0, 'Conceal', { bold = true, fg = '#4f617c' })
hi(0, 'Constant', { fg = '#c68c65' })
hi(0, 'CurSearch', { bg = '#2d4f67', bold = true, fg = '#b1d1c1' })
hi(0, 'Cursor', { bg = '#f2f1ef', fg = '#060e17' })
hi(0, 'CursorColumn', { link = 'CursorLine' })
hi(0, 'CursorLine', { bg = '#22262d' })
hi(0, 'CursorLineNr', { fg = '#f5f1e8' })
hi(0, 'DapUIBreakpointsCurrentLine', { bold = true, fg = '#97a7cb' })
hi(0, 'DapUIBreakpointsDisabledLine', { link = 'Comment' })
hi(0, 'DapUIBreakpointsInfo', { fg = '#53889f' })
hi(0, 'DapUIBreakpointsPath', { link = 'Directory' })
hi(0, 'DapUIDecoration', { fg = '#1b2639' })
hi(0, 'DapUIFloatBorder', { fg = '#1b2639' })
hi(0, 'DapUILineNumber', { fg = '#cdb070' })
hi(0, 'DapUIModifiedValue', { bold = true, fg = '#cdb070' })
hi(0, 'DapUIPlayPause', { fg = '#839e67' })
hi(0, 'DapUIRestart', { fg = '#839e67' })
hi(0, 'DapUIScope', { link = 'Special' })
hi(0, 'DapUISource', { fg = '#97a7cb' })
hi(0, 'DapUIStepBack', { fg = '#cdb070' })
hi(0, 'DapUIStepInto', { fg = '#cdb070' })
hi(0, 'DapUIStepOut', { fg = '#cdb070' })
hi(0, 'DapUIStepOver', { fg = '#cdb070' })
hi(0, 'DapUIStop', { fg = '#d41d32' })
hi(0, 'DapUIStoppedThread', { fg = '#cdb070' })
hi(0, 'DapUIThread', { fg = '#97a7cb' })
hi(0, 'DapUIType', { link = 'Type' })
hi(0, 'DapUIUnavailable', { fg = '#657a9a' })
hi(0, 'DapUIWatchesEmpty', { fg = '#d41d32' })
hi(0, 'DapUIWatchesError', { fg = '#d41d32' })
hi(0, 'DapUIWatchesValue', { fg = '#97a7cb' })
hi(0, 'DashboardCenter', { fg = '#97a7cb' })
hi(0, 'DashboardDesc', { fg = '#97a7cb' })
hi(0, 'DashboardFooter', { fg = '#657a9a' })
hi(0, 'DashboardHeader', { fg = '#d41d32' })
hi(0, 'DashboardIcon', { fg = '#4f617c' })
hi(0, 'DashboardKey', { fg = '#cdb070' })
hi(0, 'DashboardShortCut', { fg = '#cdb070' })
hi(0, 'Delimiter', { fg = '#8394af' })
hi(0, 'DiagnosticError', { fg = '#d41d32' })
hi(0, 'DiagnosticFloatingError', { fg = '#d41d32' })
hi(0, 'DiagnosticFloatingHint', { fg = '#569a88' })
hi(0, 'DiagnosticFloatingInfo', { fg = '#53889f' })
hi(0, 'DiagnosticFloatingOk', { fg = '#90bf4d' })
hi(0, 'DiagnosticFloatingWarn', { fg = '#e8a03d' })
hi(0, 'DiagnosticHint', { fg = '#569a88' })
hi(0, 'DiagnosticInfo', { fg = '#53889f' })
hi(0, 'DiagnosticOk', { fg = '#90bf4d' })
hi(0, 'DiagnosticSignError', { fg = '#d41d32' })
hi(0, 'DiagnosticSignHint', { fg = '#569a88' })
hi(0, 'DiagnosticSignInfo', { fg = '#53889f' })
hi(0, 'DiagnosticSignWarn', { fg = '#e8a03d' })
hi(0, 'DiagnosticUnderlineError', { sp = '#c34043', undercurl = true })
hi(0, 'DiagnosticUnderlineHint', { sp = '#6a9589', undercurl = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = '#658594', undercurl = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = '#dca561', undercurl = true })
hi(0, 'DiagnosticWarn', { fg = '#e8a03d' })
hi(0, 'DiffAdd', { bg = '#2b3328' })
hi(0, 'DiffChange', { bg = '#252535' })
hi(0, 'DiffDelete', { bg = '#43242b', fg = '#d41d32' })
hi(0, 'DiffText', { bg = '#49443c' })
hi(0, 'Directory', { fg = '#77a7be' })
hi(0, 'EndOfBuffer', { fg = '#060e17' })
hi(0, 'Error', { fg = '#d41d32' })
hi(0, 'ErrorMsg', { fg = '#d41d32' })
hi(0, 'Exception', { fg = '#97a7cb' })
hi(0, 'FloatBorder', { bg = '#090e13', fg = '#1b2639' })
hi(0, 'FloatFooter', { bg = '#090e13', fg = '#4f617c' })
hi(0, 'FloatTitle', { bg = '#090e13', bold = true, fg = '#4f617c' })
hi(0, 'FloatermBorder', { bg = '#090e13', fg = '#1b2639' })
hi(0, 'FoldColumn', { fg = '#4f617c' })
hi(0, 'Folded', { bg = '#1c1e25', fg = '#4f617c' })
hi(0, 'Function', { fg = '#77a7be' })
hi(0, 'GitSignsAdd', { fg = '#6a9956' })
hi(0, 'GitSignsChange', { fg = '#e8a03d' })
hi(0, 'GitSignsChangedelete', { fg = '#d41d32' })
hi(0, 'GitSignsDelete', { fg = '#d41d32' })
hi(0, 'GitSignsTopdelete', { fg = '#d41d32' })
hi(0, 'GitSignsUntracked', { fg = '#657a9a' })
hi(0, 'IblIndent', { fg = '#1b2639', nocombine = true })
hi(0, 'IblScope', { fg = '#33395b', nocombine = true })
hi(0, 'IblWhitespace', { fg = '#1b2639', nocombine = true })
hi(0, 'Identifier', { fg = '#97a7cb' })
hi(0, 'Ignore', { link = 'NonText' })
hi(0, 'IncSearch', { bg = '#dca561', fg = '#193154' })
hi(0, 'Indent', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentBlanklineChar', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentBlanklineContextChar', { fg = '#33395b', nocombine = true })
hi(0, 'IndentBlanklineContextStart', { nocombine = true, sp = '#393b44', underline = true })
hi(0, 'IndentBlanklineSpaceChar', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentBlanklineSpaceCharBlankline', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentGuide', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentGuidesEven', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentGuidesOdd', { fg = '#1b2639', nocombine = true })
hi(0, 'IndentLine', { fg = '#1b2639', nocombine = true })
hi(0, 'Italic', { italic = true })
hi(0, 'Keyword', { fg = '#97a7cb', italic = true })
hi(0, 'LazyProgressTodo', { fg = '#4f617c' })
hi(0, 'LineNr', { fg = '#4f617c' })
hi(0, 'LspCodeLens', { fg = '#657a9a' })
hi(0, 'LspReferenceText', { bg = '#22262d' })
hi(0, 'LspReferenceWrite', { bg = '#22262d', underline = true })
hi(0, 'LspSignatureActiveParameter', { fg = '#e8a03d' })
hi(0, 'MatchParen', { bold = true, fg = '#e8a03d' })
hi(0, 'MiniAnimateCursor', { nocombine = true, reverse = true })
hi(0, 'MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi(0, 'MiniClueBorder', { link = 'FloatBorder' })
hi(0, 'MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniClueDescSingle', { link = 'NormalFloat' })
hi(0, 'MiniClueNextKey', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
hi(0, 'MiniClueSeparator', { link = 'DiagnosticFloatingInfo' })
hi(0, 'MiniClueTitle', { link = 'FloatTitle' })
hi(0, 'MiniCompletionActiveParameter', { underline = true })
hi(0, 'MiniCursorword', { underline = true })
hi(0, 'MiniCursorwordCurrent', { underline = true })
hi(0, 'MiniDepsChangeAdded', { link = 'diffAdded' })
hi(0, 'MiniDepsChangeRemoved', { link = 'diffRemoved' })
hi(0, 'MiniDepsHint', { fg = '#569a88' })
hi(0, 'MiniDepsInfo', { fg = '#53889f' })
hi(0, 'MiniDepsMsgBreaking', { fg = '#e8a03d' })
hi(0, 'MiniDepsPlaceholder', { link = 'Comment' })
hi(0, 'MiniDepsTitle', { link = 'Title' })
hi(0, 'MiniDepsTitleError', { link = 'DiffDelete' })
hi(0, 'MiniDepsTitleSame', { link = 'DiffText' })
hi(0, 'MiniDepsTitleUpdate', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverAdd', { link = 'DiffAdd' })
hi(0, 'MiniDiffOverChange', { link = 'DiffText' })
hi(0, 'MiniDiffOverContext', { link = 'DiffChange' })
hi(0, 'MiniDiffOverDelete', { link = 'DiffDelete' })
hi(0, 'MiniDiffSignAdd', { fg = '#6a9956' })
hi(0, 'MiniDiffSignChange', { fg = '#e8a03d' })
hi(0, 'MiniDiffSignDelete', { fg = '#d41d32' })
hi(0, 'MiniFilesBorder', { link = 'FloatBorder' })
hi(0, 'MiniFilesBorderModified', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniFilesCursorLine', { link = 'CursorLine' })
hi(0, 'MiniFilesDirectory', { link = 'Directory' })
hi(0, 'MiniFilesFile', { fg = '#b1d1c1' })
hi(0, 'MiniFilesNormal', { link = 'NormalFloat' })
hi(0, 'MiniFilesTitle', { bg = '#090e13', bold = true, fg = '#4f617c' })
hi(0, 'MiniFilesTitleFocused', { bg = '#090e13', bold = true, fg = '#b1d1c1' })
hi(0, 'MiniHipatternsFixme', { bg = '#c34043', bold = true, fg = '#060e17' })
hi(0, 'MiniHipatternsHack', { bg = '#dca561', bold = true, fg = '#060e17' })
hi(0, 'MiniHipatternsNote', { bg = '#658594', bold = true, fg = '#060e17' })
hi(0, 'MiniHipatternsTodo', { bg = '#6a9589', bold = true, fg = '#060e17' })
hi(0, 'MiniIconsAzure', { fg = '#cdb070' })
hi(0, 'MiniIconsBlue', { fg = '#77a7be' })
hi(0, 'MiniIconsCyan', { fg = '#7ba9a5' })
hi(0, 'MiniIconsGreen', { fg = '#839e67' })
hi(0, 'MiniIconsGrey', { fg = '#b1d1c1' })
hi(0, 'MiniIconsOrange', { fg = '#c68c65' })
hi(0, 'MiniIconsPurple', { fg = '#97a7cb' })
hi(0, 'MiniIconsRed', { fg = '#97a7cb' })
hi(0, 'MiniIconsYellow', { fg = '#97a7cb' })
hi(0, 'MiniIndentscopePrefix', { nocombine = true })
hi(0, 'MiniIndentscopeSymbol', { fg = '#cdb070' })
hi(0, 'MiniJump', { link = 'SpellRare' })
hi(0, 'MiniJump2dDim', { link = 'Comment' })
hi(0, 'MiniJump2dSpot', { bold = true, fg = '#c68c65', nocombine = true })
hi(0, 'MiniJump2dSpotAhead', { bg = '#090e13', fg = '#569a88', nocombine = true })
hi(0, 'MiniJump2dSpotUnique', { bold = true, fg = '#cdb070', nocombine = true })
hi(0, 'MiniMapNormal', { link = 'NormalFloat' })
hi(0, 'MiniMapSymbolCount', { link = 'Special' })
hi(0, 'MiniMapSymbolLine', { link = 'Title' })
hi(0, 'MiniMapSymbolView', { link = 'Delimiter' })
hi(0, 'MiniNotifyBorder', { link = 'FloatBorder' })
hi(0, 'MiniNotifyNormal', { link = 'NormalFloat' })
hi(0, 'MiniNotifyTitle', { link = 'FloatTitle' })
hi(0, 'MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi(0, 'MiniPickBorder', { link = 'FloatBorder' })
hi(0, 'MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
hi(0, 'MiniPickBorderText', { link = 'FloatTitle' })
hi(0, 'MiniPickHeader', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickIconDirectory', { link = 'Directory' })
hi(0, 'MiniPickIconFile', { link = 'MiniPickNormal' })
hi(0, 'MiniPickMatchCurrent', { link = 'CursorLine' })
hi(0, 'MiniPickMatchMarked', { link = 'Visual' })
hi(0, 'MiniPickMatchRanges', { link = 'DiagnosticFloatingHint' })
hi(0, 'MiniPickNormal', { link = 'NormalFloat' })
hi(0, 'MiniPickPreviewLine', { link = 'CursorLine' })
hi(0, 'MiniPickPreviewRegion', { link = 'IncSearch' })
hi(0, 'MiniPickPrompt', { bg = '#090e13', fg = '#77a7be' })
hi(0, 'MiniStarterCurrent', { nocombine = true })
hi(0, 'MiniStarterFooter', { fg = '#638080' })
hi(0, 'MiniStarterHeader', { link = 'Title' })
hi(0, 'MiniStarterInactive', { link = 'Comment' })
hi(0, 'MiniStarterItem', { link = 'Normal' })
hi(0, 'MiniStarterItemBullet', { link = 'Delimiter' })
hi(0, 'MiniStarterItemPrefix', { fg = '#e8a03d' })
hi(0, 'MiniStarterQuery', { fg = '#53889f' })
hi(0, 'MiniStarterSection', { fg = '#90bf4d' })
hi(0, 'MiniStatuslineDevinfo', { bg = '#1c1e25', fg = '#93af93' })
hi(0, 'MiniStatuslineFileinfo', { bg = '#1c1e25', fg = '#93af93' })
hi(0, 'MiniStatuslineFilename', { bg = '#090e13', fg = '#93af93' })
hi(0, 'MiniStatuslineModeCommand', { bg = '#909398', bold = true, fg = '#060e17' })
hi(0, 'MiniStatuslineModeInsert', { bg = '#98bb6c', bold = true, fg = '#060e17' })
hi(0, 'MiniStatuslineModeNormal', { bg = '#8ba4b0', bold = true, fg = '#060e17' })
hi(0, 'MiniStatuslineModeOther', { bg = '#8ea4a2', bold = true, fg = '#060e17' })
hi(0, 'MiniStatuslineModeReplace', { bg = '#b6927b', bold = true, fg = '#060e17' })
hi(0, 'MiniStatuslineModeVisual', { bg = '#8992a7', bold = true, fg = '#060e17' })
hi(0, 'MiniTablineCurrent', { bg = '#1c1e25', bold = true, fg = '#93af93' })
hi(0, 'MiniTablineFill', { link = 'TabLineFill' })
hi(0, 'MiniTablineHidden', { bg = '#090e13', fg = '#4f617c' })
hi(0, 'MiniTablineModifiedCurrent', { bg = '#a4a7a4', bold = true, fg = '#171d33' })
hi(0, 'MiniTablineModifiedHidden', { bg = '#5c6066', fg = '#060e17' })
hi(0, 'MiniTablineModifiedVisible', { bg = '#5c6066', bold = true, fg = '#060e17' })
hi(0, 'MiniTablineTabpagesection', { bg = '#2d4f67', bold = true, fg = '#b1d1c1' })
hi(0, 'MiniTablineVisible', { bg = '#090e13', bold = true, fg = '#4f617c' })
hi(0, 'MiniTestEmphasis', { bold = true })
hi(0, 'MiniTestFail', { bold = true, fg = '#d41d32' })
hi(0, 'MiniTestPass', { bold = true, fg = '#90bf4d' })
hi(0, 'MiniTrailspace', { bg = '#c34043' })
hi(0, 'ModeMsg', { bold = true, fg = '#e8a03d' })
hi(0, 'MoreMsg', { fg = '#53889f' })
hi(0, 'MsgArea', { fg = '#93af93' })
hi(0, 'MsgSeparator', { bg = '#090e13' })
hi(0, 'NavicIconsArray', { link = 'Type' })
hi(0, 'NavicIconsBoolean', { link = 'Boolean' })
hi(0, 'NavicIconsClass', { link = 'Type' })
hi(0, 'NavicIconsConstant', { link = 'Constant' })
hi(0, 'NavicIconsConstructor', { link = '@constructor' })
hi(0, 'NavicIconsEnum', { link = 'Type' })
hi(0, 'NavicIconsEnumMember', { link = 'Constant' })
hi(0, 'NavicIconsEvent', { link = 'Structure' })
hi(0, 'NavicIconsField', { link = '@variable.member' })
hi(0, 'NavicIconsFile', { link = 'Directory' })
hi(0, 'NavicIconsFunction', { link = 'Function' })
hi(0, 'NavicIconsInterface', { link = 'Type' })
hi(0, 'NavicIconsKey', { link = 'Identifier' })
hi(0, 'NavicIconsMethod', { link = '@function.method' })
hi(0, 'NavicIconsModule', { link = '@module' })
hi(0, 'NavicIconsNamespace', { link = '@module' })
hi(0, 'NavicIconsNull', { link = 'Type' })
hi(0, 'NavicIconsNumber', { link = 'Number' })
hi(0, 'NavicIconsObject', { link = 'Type' })
hi(0, 'NavicIconsOperator', { link = 'Operator' })
hi(0, 'NavicIconsPackage', { link = '@module' })
hi(0, 'NavicIconsProperty', { link = '@property' })
hi(0, 'NavicIconsString', { link = 'String' })
hi(0, 'NavicIconsStruct', { link = 'Structure' })
hi(0, 'NavicIconsTypeParameter', { link = 'Type' })
hi(0, 'NavicIconsVariable', { link = '@variable' })
hi(0, 'NavicSeparator', { fg = '#b1d1c1' })
hi(0, 'NavicText', { fg = '#b1d1c1' })
hi(0, 'NeoTreeDimText', { fg = '#93af93' })
hi(0, 'NeoTreeGitAdded', { fg = '#6a9956' })
hi(0, 'NeoTreeGitConflict', { fg = '#d41d32' })
hi(0, 'NeoTreeGitDeleted', { fg = '#d41d32' })
hi(0, 'NeoTreeGitModified', { fg = '#e8a03d' })
hi(0, 'NeoTreeGitStaged', { fg = '#6a9956' })
hi(0, 'NeoTreeIndentMarker', { link = 'NonText' })
hi(0, 'NeoTreeModified', { link = 'String' })
hi(0, 'NeoTreeNormal', { link = 'Normal' })
hi(0, 'NeoTreeNormalNC', { link = 'Normal' })
hi(0, 'NeoTreeRootName', { bold = true, fg = '#97a7cb' })
hi(0, 'NeoTreeTabActive', { bg = '#1c1e25', bold = true, fg = '#93af93' })
hi(0, 'NeoTreeTabInactive', { bg = '#090e13', fg = '#4f617c' })
hi(0, 'NeoTreeTabSeparatorActive', { bg = '#1c1e25', fg = '#93af93' })
hi(0, 'NeoTreeTabSeparatorInactive', { bg = '#090e13', fg = '#4f617c' })
hi(0, 'NeoTreeTitleBar', { link = 'Title' })
hi(0, 'NeogitDiffAddHighlight', { bg = '#2b3328' })
hi(0, 'NeogitDiffContextHighlight', { bg = '#252535' })
hi(0, 'NeogitDiffDeleteHighlight', { bg = '#43242b' })
hi(0, 'NeogitHunkHeader', { fg = '#77a7be' })
hi(0, 'NeogitHunkHeaderHighlight', { bg = '#252535', fg = '#c68c65' })
hi(0, 'NeotestAdapterName', { fg = '#97a7cb' })
hi(0, 'NeotestDir', { fg = '#77a7be' })
hi(0, 'NeotestExpandMarker', { bold = true, fg = '#8394af' })
hi(0, 'NeotestFailed', { fg = '#d41d32' })
hi(0, 'NeotestFile', { fg = '#77a7be' })
hi(0, 'NeotestFocused', { bold = true, underline = true })
hi(0, 'NeotestIndent', { bold = true, fg = '#4f617c' })
hi(0, 'NeotestMarked', { fg = '#e8a03d', italic = true })
hi(0, 'NeotestNamespace', { fg = '#77a7be' })
hi(0, 'NeotestPassed', { fg = '#90bf4d' })
hi(0, 'NeotestRunning', { fg = '#e8a03d' })
hi(0, 'NeotestSkipped', { fg = '#cdb070' })
hi(0, 'NeotestTarget', { fg = '#97a7cb' })
hi(0, 'NeotestTest', { fg = '#93af93' })
hi(0, 'NeotestUnknown', { fg = '#638080' })
hi(0, 'NeotestWatching', { fg = '#e8a03d' })
hi(0, 'NeotestWinSelect', { fg = '#569a88' })
hi(0, 'NonText', { fg = '#4f617c' })
hi(0, 'Normal', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'NormalFloat', { bg = '#090e13', fg = '#93af93' })
hi(0, 'NormalNC', { link = 'Normal' })
hi(0, 'NotifyBackground', { bg = '#090e13' })
hi(0, 'NotifyDEBUGBorder', { link = 'Debug' })
hi(0, 'NotifyDEBUGIcon', { link = 'Debug' })
hi(0, 'NotifyDEBUGTitle', { link = 'Debug' })
hi(0, 'NotifyERRORBorder', { link = 'DiagnosticError' })
hi(0, 'NotifyERRORIcon', { link = 'DiagnosticError' })
hi(0, 'NotifyERRORTitle', { link = 'DiagnosticError' })
hi(0, 'NotifyHINTBorder', { link = 'DiagnosticHint' })
hi(0, 'NotifyHINTIcon', { link = 'DiagnosticHint' })
hi(0, 'NotifyHINTTitle', { link = 'DiagnosticHint' })
hi(0, 'NotifyINFOBorder', { link = 'DiagnosticInfo' })
hi(0, 'NotifyINFOIcon', { link = 'DiagnosticInfo' })
hi(0, 'NotifyINFOTitle', { link = 'DiagnosticInfo' })
hi(0, 'NotifyTRACEBorder', { link = 'Comment' })
hi(0, 'NotifyTRACEIcon', { link = 'Comment' })
hi(0, 'NotifyTRACETitle', { link = 'Comment' })
hi(0, 'NotifyWARNBorder', { link = 'DiagnosticWarn' })
hi(0, 'NotifyWARNIcon', { link = 'DiagnosticWarn' })
hi(0, 'NotifyWARNTitle', { link = 'DiagnosticWarn' })
hi(0, 'Number', { fg = '#b584b9' })
hi(0, 'NvimTreeExecFile', { bold = true, fg = '#839e67' })
hi(0, 'NvimTreeFolderName', { link = 'Directory' })
hi(0, 'NvimTreeGitDeleted', { fg = '#d41d32' })
hi(0, 'NvimTreeGitDirty', { fg = '#e8a03d' })
hi(0, 'NvimTreeGitNew', { fg = '#6a9956' })
hi(0, 'NvimTreeGitStaged', { fg = '#6a9956' })
hi(0, 'NvimTreeImageFile', { fg = '#97a7cb' })
hi(0, 'NvimTreeNormal', { link = 'Normal' })
hi(0, 'NvimTreeNormalNC', { link = 'NvimTreeNormal' })
hi(0, 'NvimTreeOpenedFile', { fg = '#cdb070', italic = true })
hi(0, 'NvimTreeRootFolder', { bold = true, fg = '#97a7cb' })
hi(0, 'NvimTreeSpecialFile', { fg = '#cdb070' })
hi(0, 'NvimTreeSymlink', { link = 'Type' })
hi(0, 'NvimTreeWinSeparator', { link = 'WinSeparator' })
hi(0, 'NvimTreeWindowPicker', { bg = '#090e13', bold = true, fg = '#cdb070' })
hi(0, 'Operator', { fg = '#8394af' })
hi(0, 'Pmenu', { bg = '#090e13', fg = '#f5f1e8' })
hi(0, 'PmenuExtra', { bg = '#090e13', fg = '#4f617c' })
hi(0, 'PmenuExtraSel', { bg = '#393b44', fg = '#4f617c' })
hi(0, 'PmenuKind', { bg = '#090e13', fg = '#93af93' })
hi(0, 'PmenuKindSel', { bg = '#393b44', fg = '#93af93' })
hi(0, 'PmenuSbar', { bg = '#090e13' })
hi(0, 'PmenuSel', { bg = '#393b44' })
hi(0, 'PmenuThumb', { bg = '#393b44' })
hi(0, 'PreProc', { fg = '#8394af' })
hi(0, 'Question', { link = 'MoreMsg' })
hi(0, 'QuickFixLine', { bg = '#1c1e25' })
hi(0, 'Removed', { ctermfg = 9, fg = '#ffbbb2' })
hi(0, 'Search', { bg = '#2d4f67', fg = '#b1d1c1' })
hi(0, 'SignColumn', { fg = '#4f617c' })
hi(0, 'SnacksIndent', { fg = '#1b2639', nocombine = true })
hi(0, 'SnacksIndentChunk', { fg = '#33395b', nocombine = true })
hi(0, 'SnacksIndentScope', { fg = '#33395b', nocombine = true })
hi(0, 'SnacksInputIcon', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'SnacksPicker', { bg = '#090e13' })
hi(0, 'SnacksPickerBoxTitle', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'SnacksPickerCursor', { bg = '#090e13', fg = '#060e17' })
hi(0, 'SnacksPickerDim', { fg = '#93af93' })
hi(0, 'SnacksPickerInputTitle', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'SnacksPickerListCursorLine', { bg = '#22262d', fg = '#b1d1c1' })
hi(0, 'SnacksPickerMatch', { fg = '#b1d1c1' })
hi(0, 'SnacksPickerNormal', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'SnacksPickerPickWin', { bg = '#2d4f67', bold = true, fg = '#b1d1c1' })
hi(0, 'SnacksPickerPickWinCurrent', { bg = '#090e13', bold = true, fg = '#b1d1c1' })
hi(0, 'SnacksPickerPrompt', { fg = '#b1d1c1' })
hi(0, 'SnacksPickerSelected', { fg = '#060e17' })
hi(0, 'SnacksPickerTitle', { bg = '#090e13', fg = '#b1d1c1' })
hi(0, 'Special', { fg = '#cdb070' })
hi(0, 'SpecialKey', { fg = '#4f617c' })
hi(0, 'SpellBad', { sp = '#c34043', undercurl = true })
hi(0, 'SpellCap', { sp = '#dca561', undercurl = true })
hi(0, 'SpellLocal', { sp = '#dca561', undercurl = true })
hi(0, 'SpellRare', { sp = '#dca561', undercurl = true })
hi(0, 'Statement', { fg = '#97a7cb' })
hi(0, 'StatusLine', { fg = '#93af93' })
hi(0, 'StatusLineNC', { fg = '#4f617c' })
hi(0, 'String', { fg = '#839e67' })
hi(0, 'Substitute', { bg = '#c34043', fg = '#b1d1c1' })
hi(0, 'TabLine', { fg = '#4f617c' })
hi(0, 'TabLineFill', {})
hi(0, 'TabLineSel', { bg = '#1c1e25', bold = true, fg = '#93af93' })
hi(0, 'TelescopeBorder', { bg = '#090e13', fg = '#1b2639' })
hi(0, 'TelescopeResultsClass', { link = 'Structure' })
hi(0, 'TelescopeResultsField', { link = '@field' })
hi(0, 'TelescopeResultsMethod', { link = 'Function' })
hi(0, 'TelescopeResultsStruct', { link = 'Structure' })
hi(0, 'TelescopeResultsVariable', { link = '@variable' })
hi(0, 'TelescopeSelection', { link = 'CursorLine' })
hi(0, 'TelescopeSelectionCaret', { link = 'CursorLineNr' })
hi(0, 'TelescopeTitle', { fg = '#4f617c' })
hi(0, 'Title', { bold = true, fg = '#77a7be' })
hi(0, 'Todo', { bg = '#658594', bold = true, fg = '#193154' })
hi(0, 'TreesitterContext', { link = 'Folded' })
hi(0, 'TreesitterContextLineNumber', { fg = '#4f617c' })
hi(0, 'TroubleIndent', { fg = '#33395b' })
hi(0, 'TroublePos', { fg = '#4f617c' })
hi(0, 'Type', { fg = '#7ba9a5' })
hi(0, 'Underlined', { fg = '#cdb070', underline = true })
hi(0, 'Visual', { bg = '#393b44' })
hi(0, 'WarningMsg', { fg = '#e8a03d' })
hi(0, 'WhichKeyIconAzure', { link = 'MiniIconsAzure' })
hi(0, 'WhichKeyIconBlue', { link = 'MiniIconsBlue' })
hi(0, 'WhichKeyIconCyan', { link = 'MiniIconsCyan' })
hi(0, 'WhichKeyIconGreen', { link = 'MiniIconsGreen' })
hi(0, 'WhichKeyIconGrey', { link = 'MiniIconsGrey' })
hi(0, 'WhichKeyIconOrange', { link = 'MiniIconsOrange' })
hi(0, 'WhichKeyIconPurple', { link = 'MiniIconsPurple' })
hi(0, 'WhichKeyIconRed', { link = 'MiniIconsRed' })
hi(0, 'WhichKeyIconYellow', { link = 'MiniIconsYellow' })
hi(0, 'Whitespace', { fg = '#33395b' })
hi(0, 'WildMenu', { link = 'Pmenu' })
hi(0, 'WinBar', { fg = '#93af93' })
hi(0, 'WinBarNC', { fg = '#93af93' })
hi(0, 'WinSeparator', { fg = '#060e17' })
hi(0, 'debugBreakpoint', { fg = '#cdb070' })
hi(0, 'debugPC', { bg = '#43242b' })
hi(0, 'diffAdded', { fg = '#6a9956' })
hi(0, 'diffChanged', { fg = '#e8a03d' })
hi(0, 'diffDeleted', { fg = '#d41d32' })
hi(0, 'diffNewFile', { fg = '#6a9956' })
hi(0, 'diffOldFile', { fg = '#d41d32' })
hi(0, 'diffRemoved', { fg = '#d41d32' })
hi(0, 'healthError', { fg = '#d41d32' })
hi(0, 'healthSuccess', { fg = '#90bf4d' })
hi(0, 'healthWarning', { fg = '#e8a03d' })
hi(0, 'lCursor', { link = 'Cursor' })
hi(0, 'markdownCode', { fg = '#839e67' })
hi(0, 'markdownCodeBlock', { fg = '#839e67' })
hi(0, 'qfFileName', { link = 'Directory' })
hi(0, 'qfLineNr', { link = 'LineNr' })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = '#090e13'
g.terminal_color_1 = '#c4746e'
g.terminal_color_2 = '#8a9a7b'
g.terminal_color_3 = '#c4b28a'
g.terminal_color_4 = '#8ba4b0'
g.terminal_color_5 = '#a292a3'
g.terminal_color_6 = '#c5c9c7'
g.terminal_color_7 = '#a4a7a4'
g.terminal_color_8 = '#909398'
g.terminal_color_9 = '#e46876'
g.terminal_color_10 = '#87a987'
g.terminal_color_11 = '#e6c384'
g.terminal_color_12 = '#7fb4ca'
g.terminal_color_13 = '#938aa9'
g.terminal_color_14 = '#7aa89f'
g.terminal_color_15 = '#c5c9c7'
